### PR TITLE
Add unittests

### PR DESCRIPTION
**Pull request by ClasherKasten**
Disclaimer:
With some testcases I tried to force some behaviour that I thought is in the spirit of this library. Feel free to implement or reject it.

Roadmap:
- [X] Functions
    - [X] AnsiSequences
    - [X] Constraints
    - [X] DunderFunctions
    - [X] General
    - [X] StrictTyping
- [ ] Color
    - [ ] ColorObjectConversion
    - [ ] ColorSystem
        - [x] RGB
        - [x] HEX
        - [ ] RGBA
        - [ ] HEXA
        - [x] HSL
        - [x] HSV
        - [ ] CMYK
    - [ ] ColorTupleConversion
- [ ] Console/Styling
    - [ ] Inline
        - [ ] Bodies
        - [ ] MakeUp
        - [ ] RgbControlled
    - [ ] Nested
        - [ ] Bodies
        - [ ] MakeUp
        - [ ] RgbControlled

Not all of these modules require tests, i just listed them and we can discuss everything else in the comments of this PR

### CODE REVIEW

**Comment by ClasherKasten** [comment]
The whole library isn't compatible with python3.7 because of some walrus operators in the `StrictTyping` module (especially in the `StrictOutput` class)

**Comment by AnnaSasDev** [comment]
> The whole library isn't compatible with python3.7 because of some walrus operators in the `StrictTyping` module (especially in the `StrictOutput` class)

This should now be fixed in the latest #8 4.0.0_proposal

**Comment by AnnaSasDev** [comment]
@ClasherKasten I fixed the keyword argument for control_code in the 4.0.0 proposal #8 , but I also see the 'issue' with the pow() FIXME's
I had the same issue with myself when I wrote it. looking at it now, I'd just move forward renaming it to power(). It's not as clean as the other functions in the same file, but it will get the job done

**Comment by AnnaSasDev** [comment]
Due to inactivity I've taken the liberty to expand a little on the package. This lead to too much to rewrite for the current testing.
The help you gave is greatly appreciated, but unfortunately I'm going to close this pull request

**Pull request closed without merging**
